import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono } from "next/font/google";
import { Gabarito } from 'next/font/google'
import { Comfortaa } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";
import { AppKit } from "@/context/web3modal";

const inter = Inter({ subsets: ["latin"] });

const gabarito = Gabarito({
  subsets: ['latin'],
  display: 'swap',
});

const comfortaa = Comfortaa({
  subsets: ['latin'],
  display: 'swap',
});

const ibm_plex_mono_heading = IBM_Plex_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

const ibm_plex_mono_body = IBM_Plex_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
  weight: ["100", "200", "300", "400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('antialiased', ibm_plex_mono_heading.variable, ibm_plex_mono_body.variable)}>
        <AppKit>
          {children}
        </AppKit>
      </body>
    </html>
  );
}
